# Generated by Django 5.0.1 on 2024-01-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
