# Generated by Django 5.0.1 on 2024-01-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summary', '0002_delete_item_delete_video'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalText', models.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summaryText', models.TextField()),
                ('preprocessed_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.preprocessedvideo')),
            ],
        ),
    ]
