# Generated by Django 5.0.1 on 2024-01-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_comment', '0002_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='emotion',
            new_name='message',
        ),
    ]
