# Generated by Django 5.0.1 on 2024-01-12 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('channel_title', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('paid_product_placement', models.BooleanField(default=False)),
            ],
        ),
    ]
